version: '3'
services:
  python3_jd:
    build: ./deploy
    container_name: python3_jd
    volumes:
      - /var/log/jd_coupon_spiders:/app/log
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped


