version: '3'
services:
  python3_jd:
    build: .
    container_name: python3_jd
    volumes:
      - /var/www/envs/jd_coupon_spiders/settings.py:/app/jd_coupon_spiders/settings.py
      - /var/log/jd_coupon_spiders:/app/log
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    ports:
      - 5922:5922


