version: '3'
services:
  python3_jd:
    build: ./deploy
    container_name: python3_jd
    volumes:
      - /var/www/python_project/jd_coupon_spiders:/app
      - /var/www/envs/jd_coupon_spiders/settings.py:/app/jd_coupon_spiders/spiders/settings.py
    environment:
      - TZ=Asia/Shanghai


